kill(all);

load("pw.mac");
plusfun(x)::= (signum(x) + 1)/2 * x;
ww(s)::= plusfun(1-abs(s))^6*(1+6*abs(s)+35/3*(s)^2);

c(s):= 1/6*(eps*ww(2*s)-ww(2*s-1)-ww(2*s+1));

plot2d([c(x)], [x, -1, 1]);

intfun(ndim, f)::= buildq([ndim, f],
  if ndim=1 then 2*f else if ndim=2 then 2*%pi*f*r else if ndim=3 then 4*%pi*f*r^2);

ndim: 2;
load("nint.mac");
eq: pwint(intfun(ndim, c(r)*r^2), r, 0, 1)=0;
grind(solve(eq, eps));

I: 1/pwint(intfun(ndim, c(r)), r, 0, 1);
grind(fullratsimp(I));