(kill(all),0);
0$

(kill(all),
 load("sph-kernel.mac"),
 load("nint.mac"),
   0);
0$

(ndim: 2,
 cutoff: 1/2,
 define_kernel(ndim, cutoff, 'wendland6, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/2,
 define_kernel(ndim, cutoff, 'lucy, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/2,
 define_kernel(ndim, cutoff, 'quintic, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/2,
 define_kernel(ndim, cutoff, 'cubic, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/2,
 define_kernel(ndim, cutoff, 'laguerrewendland4, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 2,
 cutoff: 1/2,
 define_kernel(ndim, cutoff, 'laguerrewendland4, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerregaussian, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerrewendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerrewendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

/* chech if the second moment is zero */
(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerrewendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre1wendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$

(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre1wendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$

(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre1wendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre1wendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) ,
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre2wendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre2wendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) ,
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

/* chech if the second moment is zero */
(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre2wendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$


(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre2wendland4eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) ,
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

/* chech if the second moment is zero */
(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre2wendland6eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre2wendland6eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre2wendland6eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) ,
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre2wendland6eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) ,
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$


(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre4wendland6eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) ,
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre4wendland6eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) ,
 is(abs(nint(intfun, x, 0, 2*cutoff) - 1.0) < 1e-8)
);
true$

(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre4wendland6eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'laguerre4wendland6eps, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$

(ndim: 3,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'blincomb, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$

(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'blincomb, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$

/* chech if the second moment is zero */
(ndim: 2,
 cutoff: 1/8,
 define_kernel(ndim, cutoff, 'blincomb, 'w, 'dw),
 intfun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x) * x^2,
 is(abs(nint(intfun, x, 0, 2*cutoff)) < 1e-8)
);
true$
