load ("vector");
load ("eigen");

norm2D: 1.591549430918954/h^ndim;
norm3D: 2.088908628081126/h^ndim;
norm[2]: norm2D;
norm[3]: norm3D;

/* vector abs */
vabs(R):= sqrt(R.R);
wvect(s):= (1+3*s)*(1-s)^3$
dwall(x):= ''(diff(wvect(x), x))$
w(x):= norm[ndim]*wvect(vabs(x)/h)$
dwdx(x):= norm[ndim]/h*dwall(vabs(x)/h)$
infun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x);
infun_dw(x):= 2^(ndim-1)*%pi*x^(ndim-1)*dwdx(x);

/* check normalization of the kernel*/
quad_qags(infun(x), x, 0, cutoff);