load ("vector");
load ("eigen");

ndim: 2;
norm2D: 1.5915494309189533576;
norm3D: 2.154187022708661;
norm[2]: norm2D;
norm[3]: norm3D;

/* vector abs */
vabs(R):= sqrt(R.R);
wvect(s):= (1 - s^2)^4;
dwall(x):= ''(diff(wvect(x), x))$
w(x):= norm[ndim]*wvect(vabs(x)/h)$
dwdx(x):= norm[ndim]/h*dwall(vabs(x)/h)$
infun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x);
infun_dw(x):= 2^(ndim-1)*%pi*x^(ndim-1)*dwdx(x);

/* check normalization of the kernel*/
quad_qags(infun(x), x, 0, cutoff);