* gland geometry

Inlet:
107*10^(-6) m
Outlet:
10*10^(-6) m

Length:
18*10^(-3) m

beta-sheets size:
10*10^(-9) nm

* reviews
** From the Spinning Structure ucture of Silk Fibers Glands to the by Raman Spectromicroscopy: From the Spinning Glandthe Fibers

the native dope is typical of unfolded proteins, which is in agreement
with the literature.[73][74][75][76]

The conformation of the spinning dope that has flowed out of the gland
is basi- cally identical to the native silk contained in the sac of
the gland, and is slightly affected by dehydration.

The spectra have been obtained in the dry state and provide a snapshot
of the events occurring in the canal. Typical polarized spectra (XX
and ZZ polarizations) at different locations (in the glandular sac,
after the draw down taper and after the valve) are shown in
Figure 8. The spectra show that the proteins are in their native state
and that the spinning dope is initially isotropic. This remains the
case until the draw down taper, but b-sheets start to develop between
the second and the third limb of the duct, suggesting that early
b-sheets are generated by shear forces. These early b-sheets might
play the role of nucleation sites for the subsequent b-sheet
aggregation. The spectra recorded after the valve show that the
alignment of the polypeptides chains occurs near the valve, revealing
that orientational and conformational changes do not occur
simultaneously. Thus, extensional ﬂow seems to be the driving force to
produce the orientational order, which in turn is associated with the
formation of the major part of the b-sheets.
