load("pw.mac");

norm[2]: 63/(478*%pi);
norm[3]: 9/(40*%pi);

fsim: [
(3 - s)^5 - 6*(2 - s)^5 + 15*(1 - s)^5,
(3 - s)^5 - 6*(2 - s)^5,
(3 - s)^5
];
dfsim: diff(fsim, s);

wvect(s):=''(pw([-1,fsim[1],1,fsim[2],2,fsim[3], 3, 0, inf], s));
dwvect(s):=''(pw([-1,dfsim[1],1,dfsim[2],2,dfsim[3], 3, 0, inf], s));

w(R):= norm[ndim]*wvect(3*vabs(R)/cutoff)/cutoff^ndim;
dwdr(R):= 3*norm[ndim]/cutoff*dwvect(3*vabs(R)/cutoff)/cutoff^ndim;

test_kernel(ndim, cutoff):= block([cutoff, infun],
  infun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x),
  quad_qags(infun(x), x, 0, cutoff)
  );

/* cutoff: 1e-5; */
/* ndim: 2; */
/* infun(x):= 2^(ndim-1)*%pi*x^(ndim-1)*w(x); */
/* plot2d(w(x), [x, 0, cutoff]); */
/* plot2d(infun(x), [x, 0, cutoff]); */
/* quad_qags(infun(x), x, 0, cutoff); */